### ISSUE TITLE
Can`t find link which to create the repository

### ISSUE THREAD

**Issue by FoxerLee** [jccosta/CS-GY-6533#1]
Dear Prof:

1. May I ask when can we receive the link to create our own repository? 
2. Would you provide some references for setting up Travis?
3. When can we post questions on NYU Classes forum? Now the forum is still unavailable... 

Thanks! :)

**Comment by jccosta** [comment]
Hi,

1. We are working on that. I believe you will get the link soon.
2. I will send the info together with the link.
3. The forums are online.

Next time, use the issue tracking system for software related issues.

Jonathas.
